server:
  port: 8082


spring:
  application:
    name: tts-service
  jvm:
    args: --enable-native-access=ALL-UNNAMED

# Nacos 服务注册发现配置
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848  # Nacos 服务端地址
      discovery:
        namespace: public  # 命名空间 (public 为默认命名空间)
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: public

chattts:
  python:
    path: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe  # 请根据您的Python安装路径修改
  script:
    path: D:\ideaProject\ChatTTS\examples\cmd\run.py  # 请根据您的ChatTTS安装路径修改
  model:
    path: D:\ideaProject\ChatTTS\